Repository WEB16KJN/Client, pull requests merged in 2021-12, with the labels that each got.

#49 문의하기 목록에 API 붙이기
  src/api/common/constants.js
  src/api/question.js
  src/components/question/search/QuestionTable.jsx
  src/pages/question/SearchQuestion.jsx
Labels: feature 🌸

#50 :hammer: mock-main-api >> src/data/main.json으로 변경
  src/components/main/ArticleContent.jsx
  src/components/main/ArticleContents.jsx
  src/components/main/ArticleNav.jsx
  src/components/main/OptionContent.jsx
  src/components/main/OptionContents.jsx
  src/data/main/articles.json
  src/data/main/options.json
Labels: chore 🦾

#53 Feat/#46 서버에 보내줄 문의 정보 한 객체로 모으기 #46
  src/components/question/create/CreateFormTable.jsx
  src/components/question/create/CreateInput.jsx
  src/components/question/create/FileInput.jsx
  src/components/question/create/FileInputs.jsx
  src/pages/question/CreateQuestion.jsx
Labels: feature 🌸

#57 Feat/#54 1:1 문의하기 글쓰기 폼, 프로필+스케줄 바 반응형 구현
  src/assets/ic_member_small.svg
  src/components/common/Icon.js
  src/components/question/Profile.jsx
  src/components/question/Profile.layout.jsx
  src/components/question/ProfileScheduleBar.jsx
  src/components/question/ProfileScheduleBar.layout.jsx
  src/components/question/ProfileScheduleWrapper.jsx
  src/components/question/QuestionBottom.layout.jsx
  src/components/question/QuestionTopLayout.layout.jsx
  src/components/question/Slider.layout.jsx
  src/components/question/create/BackOrSubmit.jsx
  src/components/question/create/BackOrSubmit.layout.jsx
  src/components/question/create/CreateFormTable.jsx
  src/components/question/create/CreateFormTable.layout.jsx
  src/components/question/create/FileInput.jsx
  src/components/question/create/FileInput.layout.jsx
  src/components/question/create/TableCell.jsx
  src/components/question/create/TableRow.layout.jsx
  src/pages/question/Question.jsx
Labels: style 💐

#60 Feat/#58 스케줄 GET, 문의하기 POST 구현
  src/api/common/request.js
  src/api/question.js
  src/components/question/Schedule.jsx
  src/components/question/ScheduleUnit.jsx
  src/components/question/create/BackOrSubmit.jsx
  src/components/question/create/BackOrSubmit.layout.jsx
  src/components/question/create/CreateFormTable.jsx
  src/pages/question/CreateQuestion.jsx
Labels: feature 🌸

#56 feat: Main/Options 옵션 선택 영역 반응형 구현 완료
  src/components/main/InputSelf.jsx
  src/components/main/Option.Layout.jsx
  src/components/main/Option.jsx
  src/components/main/OptionContent.jsx
  src/components/main/OptionContents.jsx
  src/components/main/SearchBox.jsx
Labels: feature 🌸

#66 :lipstick: 문의하기 조회 뷰 관련 레이아웃 반응형 적용
  src/components/question/search/DateSelector.jsx
  src/components/question/search/DateSelector.layout.jsx
  src/pages/question/SearchQuestion.jsx
Labels: style 💐

#68 feat: Main/Options 모바일 뷰 구현
  src/components/main/InputSelf.jsx
  src/components/main/Option.Layout.jsx
  src/components/main/OptionContent.jsx
Labels: feature 🌸

#70 Feat/#69 글쓰기 폼 input 디테일 추가
  src/components/question/create/CreateFormTable.jsx
  src/components/question/create/CreateInput.jsx
  src/components/question/create/TelInput.jsx
  src/pages/question/CreateQuestion.jsx
Labels: feature 🌸

#72 Feat/#71 종이 검색 구현
  src/api/paper.js
  src/components/main/ArticleContent.jsx
  src/components/main/ArticleContents.jsx
  src/components/main/InputSelf.jsx
  src/components/main/Option.jsx
  src/components/main/OptionContent.jsx
  src/components/main/OptionContents.jsx
  src/components/main/PageNav.jsx
  src/components/main/SearchBox.jsx
  src/data/main/articles.json
  src/data/main/options.json
  src/pages/Main.jsx
  src/utils/articlesReducer.js
  src/utils/createQuery.js
  src/utils/mainReducer.js
  src/utils/stringHandler.js
Labels: feature 🌸

#74 feat: 게시글 좋아요 기능 구현
  src/api/paper.js
  src/components/main/ArticleContent.jsx
  src/utils/articlesReducer.js
  src/utils/mainReducer.js
Labels: feature 🌸
