Repository WEB16KJN/Client, pull requests merged in 2021-11, with the labels that each got.

#4 ➕ json-server 설치 / mock-data 생성
  .gitignore
  mock-data/mock-main-api.json
  mock-data/mock-question-api.json
  package-lock.json
  package.json
Labels: chore 🦾

#6 컴포넌트 구성 및 라우터 연결
  src/App.jsx
  src/component/common/Footer.jsx
  src/component/common/Header.jsx
  src/pages/Main.jsx
  src/pages/question/CreateQuestion.jsx
  src/pages/question/Question.jsx
  src/pages/question/SearchQuestion.jsx
Labels: feature 🌸, chore 🦾

#11 💄 컬러 전역 변수 선언
  src/styles/color.js
Labels: chore 🦾

#12 이미지 및 폰트 에셋 추가, css 초기화
  public/favicon.ico
  public/index.html
  src/App.jsx
  src/component/common/Icon/assets/ic_arrow_next.svg
  src/component/common/Icon/assets/ic_arrow_next_thin.svg
  src/component/common/Icon/assets/ic_arrow_previous.svg
  src/component/common/Icon/assets/ic_arrow_rect_up.svg
  src/component/common/Icon/assets/ic_calender.svg
  src/component/common/Icon/assets/ic_check_false.svg
  src/component/common/Icon/assets/ic_check_round_true.svg
  src/component/common/Icon/assets/ic_check_true.svg
  src/component/common/Icon/assets/ic_facebook.svg
  src/component/common/Icon/assets/ic_heart.svg
  src/component/common/Icon/assets/ic_instagram.svg
  src/component/common/Icon/assets/ic_like_false.svg
  src/component/common/Icon/assets/ic_like_true.svg
  src/component/common/Icon/assets/ic_logout.svg
  src/component/common/Icon/assets/ic_looks.svg
  src/component/common/Icon/assets/ic_move_last.svg
  src/component/common/Icon/assets/ic_move_next.svg
  src/component/common/Icon/assets/ic_search.svg
  src/component/common/Icon/assets/ic_search_big.svg
  src/component/common/Icon/assets/ic_toggle_down.svg
  src/component/common/Icon/assets/ic_toggle_open.svg
  src/component/common/Icon/assets/ic_toggle_up.svg
  src/component/common/Icon/assets/ic_user.svg
  src/component/common/Icon/assets/logo.svg
  src/component/common/Icon/index.js
  src/styles/GlobalStyle.js
Labels: chore 🦾

#13 🔨 Main 레이아웃 설계
  src/component/main/Article.jsx
  src/component/main/ArticleContents.jsx
  src/component/main/ArticleNav.jsx
  src/component/main/Intro.jsx
  src/component/main/Option.jsx
  src/component/main/PageNav.jsx
  src/component/main/SearchBox.jsx
  src/pages/Main.jsx
Labels: feature 🌸, style 💐

#17 💄 컬러 값 수정 사항 반영
  src/styles/color.js
Labels: chore 🦾

#21 문의하기 뷰 중 좌측 내비바 스타일 구현
  src/component/question/SideNav.jsx
  src/pages/question/Question.jsx
Labels: style 💐

#22 🚧 1:1 문의 페이지 - 글쓰기, 프로필, 캘린더 구현 진행 중
  package-lock.json
  package.json
  src/component/common/Icon/assets/ic_member.svg
  src/component/common/Icon/assets/ic_user.svg
  src/component/common/Icon/index.js
  src/component/question/Calendar.jsx
  src/component/question/CalendarUnit.jsx
  src/component/question/Profile.jsx
  src/component/question/ProfileCalendar.jsx
  src/component/question/create/BackOrSubmit.jsx
  src/component/question/create/CreateFormTable.jsx
  src/component/question/create/CreateInput.jsx
  src/component/question/create/CreateTitle.jsx
  src/component/question/create/FileInput.jsx
  src/component/question/create/TableCell.jsx
  src/pages/question/CreateQuestion.jsx
  src/pages/question/Question.jsx
Labels: help wanted 🎀, feature 🌸, style 💐

#26 :memo: 리드미 작성
  readme.md
Labels: docs 📜

#19 문의하기 검색 뷰 구현
  src/component/question/Title.jsx
  src/component/question/create/CreateFormTable.jsx
  src/component/question/create/CreateTitle.jsx
  src/component/question/search/DateSelector.jsx
  src/component/question/search/QuestionTable.jsx
  src/pages/question/CreateQuestion.jsx
  src/pages/question/Question.jsx
  src/pages/question/SearchQuestion.jsx
  src/utils/dateSelector.js
Labels: style 💐

#34 문의 글쓰기 정보 state 선언 및 input 핸들링
  src/component/question/create/BackOrSubmit.jsx
  src/component/question/create/CreateFormTable.jsx
  src/component/question/create/CreateInput.jsx
  src/component/question/create/FileInput.jsx
  src/pages/question/CreateQuestion.jsx
  src/pages/question/Question.jsx
Labels: feature 🌸

#37 ➕ react-responsive 설치
  package-lock.json
  package.json
Labels: chore 🦾

#39 💄 1:1 문의하기 페이지 전체 width 및 문의 글쓰기 영역 width 설정
  src/pages/question/CreateQuestion.jsx
  src/pages/question/Question.jsx
  src/pages/question/SearchQuestion.jsx
Labels: help wanted 🎀, style 💐

#40 Feat/#31
  src/components/question/Calendar.jsx
  src/components/question/CalendarUnit.jsx
  src/components/question/Profile.jsx
  src/components/question/create/CreateFormTable.jsx
Labels: style 💐

#44 Feat/#43
  src/api/common/constants.js
  src/api/common/request.js
  src/api/paper.js
  src/api/question.js
  src/api/user.js
  src/components/common/Base.layout.jsx
  src/components/common/Error.jsx
  src/components/question/Profile.jsx
  src/utils/stringHandler.js
Labels: feature 🌸, chore 🦾
